export const SET_ALL_FILENAMES = "SET_ALL_FILENAMES";

export const DROPZONE_OPEN = "DROPZONE_OPEN";
export const DROPZONE_SET_FILES = "DROPZONE_SET_FILES";
export const DROPZONE_CLEAR = "DROPZONE_CLEAR";
export const DROPZONE_CLOSE = "DROPZONE_CLOSE";

export const PASSWORD_DIALOG_OPEN = "PASSWORD_DIALOG_OPEN";
export const PASSWORD_DIALOG_CLOSE = "PASSWORD_DIALOG_CLOSE";
export const PASSWORD_DIALOG_INPUT_CHANGE = "PASSWORD_DIALOG_INPUT_CHANGE";

export const SEND_FILES_FAILURE = "SEND_FILES_FAILURE";
export const SEND_FILES_SUCCESS = "SEND_FILES_SUCCESS";

export const SNACKBAR_ADD_NEW = "SNACKBAR_ADD_NEW";
export const SNACKBAR_DISPLAY_NEXT = "SNACKBAR_DISPLAY_NEXT";
export const SNACKBAR_HIDE_CURRENT = "SNACKBAR_HIDE_CURRENT";
export const SNACKBAR_REMOVE_CURRENT = "SNACKBAR_REMOVE_CURRENT";

export const DELETION_DIALOG_OPEN = "DELETION_DIALOG_OPEN";
export const DELETION_DIALOG_CHANGE_INPUT = "DELETION_DIALOG_CHANGE_INPUT";
export const DELETION_DIALOG_CANCEL = "DELETION_DIALOG_CANCEL";
export const DELETION_DIALOG_WRONG_FILENAME = "DELETION_DIALOG_WRONG_FILENAME";

export const CODE_EDITOR_OPEN = "CODE_EDITOR_OPEN";
export const CODE_EDITOR_CLOSE = "CODE_EDITOR_CLOSE";
export const CODE_EDITOR_SET_CODE = "CODE_EDITOR_SET_CODE";
export const CODE_EDITOR_SAVE_SUCCESS = "CODE_EDITOR_SAVE_SUCCESS";

export const CONFIG_NOT_FOUND = "CONFIG_NOT_FOUND";
export const CONFIG_SET = "CONFIG_SET";
export const CONFIG_RESTART = "CONFIG_RESTART";
